version: "2"
services:
  postgres:
    env_file: ./.env
    image: postgres:latest
    ports:
    - 5432:5432
  sanic:
    env_file: ./.env
    command: uvicorn demo.main:app --host 0.0.0.0
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
