version: "2"
services:
  postgres:
    env_file: ./.env
    image: postgres:latest
    ports:
    - 5432:5432
  sanic:
    env_file: ./.env
    build: .
    command: python3 fast_api/main.py
    depends_on:
      - postgres
    ports:
      - 8888:8888